name: Tokenkit Indexer Redeploy

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sops
        run: |
          curl -Lo sops https://github.com/mozilla/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/sops

      - name: Set up age for decryption
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.AGE_PRIVATE_KEY }}" > ~/.config/sops/age/keys.txt

      - name: Decrypt .env file
        run: sops --decrypt secret.env > .env

      - name: Install SSH Client
        run: sudo apt-get install -y sshpass

      - name: Transfer files to contabo
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ env.CONTABO_IP }}
          username: root
          key: ${{ env.CONTABO_SSH_KEY }}
          source: "."
          target: "/home/starknet_indexer_v1/"
        env:
          CONTABO_IP: ${{ secrets.CONTABO_HOST }}
          CONTABO_SSH_KEY: ${{ secrets.CONTABO_SSH_KEY }}

      - name: Setup Indexer
        env:
          VPS_PASSWORD: ${{ secrets.CONTABO_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.CONTABO_USER }}@${{ secrets.CONTABO_HOST }} << 'EOF'
            # Navigate to indexer directory
            cd "/home/starknet_indexer_v1/"

            pnpm install

            #  Restart services
            sudo systemctl start starknet_indexer_sepolia_v1 starknet_indexer_mainnet_v1

            exit 0  # Exit from SSH session
          EOF