name: Tokenkit Indexer system setup

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sops
        run: |
          curl -Lo sops https://github.com/mozilla/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/sops

      - name: Set up age for decryption
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.AGE_PRIVATE_KEY }}" > ~/.config/sops/age/keys.txt

      - name: Decrypt .env file
        run: |
          sops --decrypt mainnet.secret.env > .mainnet.env
          sops --decrypt sepolia.secret.env > .sepolia.env

          sops --decrypt tokenkit_mainnet.secret.env > .tokenkit_mainnet.env
          sops --decrypt tokenkit_sepolia.secret.env > .tokenkit_sepolia.env


      - name: Install SSH Client
        run: sudo apt-get install -y sshpass

      - name: Transfer files to contabo
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ env.CONTABO_IP }}
          username: root
          key: ${{ env.CONTABO_SSH_KEY }}
          source: "."
          target: "/home/starknet_indexer_v2/"
        env:
          CONTABO_IP: ${{ secrets.CONTABO_HOST }}
          CONTABO_SSH_KEY: ${{ secrets.CONTABO_SSH_KEY }}

      - name: Setup Indexer
        env:
          VPS_PASSWORD: ${{ secrets.CONTABO_PASSWORD }}

        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.CONTABO_USER }}@${{ secrets.CONTABO_HOST }} << 'EOF'
          
            export INDEXER_IDENTIFIER="starknet_indexer_v2"

            # Navigate to indexer directory
            cd /home/$INDEXER_IDENTIFIER/

            pwd

            pnpm install

            # Create the templated Starknet Indexer (To index transfer events) systemd service
            echo "
            [Unit]
            Description=Starknet Indexer (%i)
            After=network.target

            [Service]
            User=root
            Group=root
            WorkingDirectory=/home/$INDEXER_IDENTIFIER/
            Restart=always
            ExecStart=/root/.local/share/apibara/bin/apibara run \
                --allow-env=/home/$INDEXER_IDENTIFIER/.%i.env \
                /home/$INDEXER_IDENTIFIER/transfers_indexer.ts \
                -A \${secrets.APIBARA_DNA_KEY} \
                --persist-to-fs /home/$INDEXER_IDENTIFIER/apibara_store \
                --sink-id starknet_%i

            [Install]
            WantedBy=multi-user.target
            " | sudo tee /etc/systemd/system/"$INDEXER_IDENTIFIER"_transfers.service > /dev/null

            # Create the templated Starknet Tokenkit Indexer (To index tokenkit contract events) systemd service
            echo "
            [Unit]
            Description=Tokenkit Indexer (%i)
            After=network.target

            [Service]
            User=root
            Group=root
            WorkingDirectory=/home/$INDEXER_IDENTIFIER/
            Restart=always
            ExecStart=/root/.local/share/apibara/bin/apibara run \
                --allow-env=/home/$INDEXER_IDENTIFIER/.%i.env \
                /home/$INDEXER_IDENTIFIER/tokenkit_indexer.ts \
                -A \${secrets.APIBARA_DNA_KEY} \
                --persist-to-fs /home/$INDEXER_IDENTIFIER/apibara_store \
                --sink-id starknet_%i

            [Install]
            WantedBy=multi-user.target
            " | sudo tee /etc/systemd/system/"$INDEXER_IDENTIFIER"_tokenkit.service > /dev/null


            # Enable and start services
            sudo systemctl daemon-reload

            sudo systemctl enable "$INDEXER_IDENTIFIER"_transfers@mainnet.service
            sudo systemctl enable "$INDEXER_IDENTIFIER"_transfers@sepolia.service

            sudo systemctl enable "$INDEXER_IDENTIFIER"_tokenkit@tokenkit_mainnet.service
            sudo systemctl enable "$INDEXER_IDENTIFIER"_tokenkit@tokenkit_sepolia.service


            # Start the services
            sudo systemctl start "$INDEXER_IDENTIFIER"_transfers@mainnet.service
            sudo systemctl start "$INDEXER_IDENTIFIER"_transfers@sepolia.service

            sudo systemctl start "$INDEXER_IDENTIFIER"_tokenkit@tokenkit_mainnet.service
            sudo systemctl start "$INDEXER_IDENTIFIER"_tokenkit@tokenkit_sepolia.service
           

            exit 0  # Exit from SSH session
          EOF